# Generated by Django 2.2.3 on 2019-08-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190803_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_login',
            name='name',
        ),
    ]
